### PR TITLE
revert back to using tar balls of github tags

### PR DESCRIPTION
**Pull request by AmeBel**

### CODE REVIEW

**Comment by linas** [comment]
Why? This is a really bad idea. github tarballs a f**ed up. and should not be used for anything, ever.  I would disable the feature if I could, but I can't; its a github mis-design.

**Comment by AmeBel** [comment]
The tar ball is just the archive of the state when a tag is created, so unless there is an issue with building and installing using git clone. I don't see the issue with using the tag archives. 

With regards to github releases, releases and tag archives are different. This division might be a mis-design, I don't know. But, if you choose to make releases there is both a gui and cli options see https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release . Maybe even this is a mis-design, then there is on option of using one of these github actions https://github.com/marketplace?type=actions&query=release+

**Comment by AmeBel** [comment]
You are not the only one who think it is a mis-design https://github.community/t/tag-without-release/857

**Comment by linas** [comment]
The problem is that the tarballs that github provides cannot be built -- as you yourself experienced just a few days ago!  This is generically true for *all* the tarballs that github provides: they require special tools, techniques and configurations that users are not aware of, and do not have access to. In particular, the README does not explain how to build a github tarball, it only explains how to build ordinary release tarballs.

**Pull request merged**
