### PR TITLE
Fix bug when using octool in i686 machines.

### PR DESCRIPTION
**Pull request by MarcosPividori**

### CODE REVIEW

**Comment by AmeBel** [comment]
thanks

**Comment by AmeBel** [comment]
@MarcosPividori 

Independent of the state of this script, I tried `cabal install stack` and get
```
>> cabal install stack
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: stack-0.1.3.1
rejecting: base-4.6.0.1/installed-8aa... (conflict: stack => base>=4.7 && <5)
rejecting: base-4.8.1.0, 4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0,
4.5.1.0, 4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1,
4.2.0.0, 4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires
installed instance)
```
any clue what it means?

**Comment by MarcosPividori** [comment]
Hi @AmeBel !
You shouldn't directly use cabal to install stack.
This dependency problem you get is very common when working with haskell packages using cabal. Because of that, stack comes to solve these kind of problems.
So, we don't directly use cabal, we use stack.

**Comment by AmeBel** [comment]
I was trying to simplify the script so that people don't have to deal with another hassel of installing stack on i686 system. I will add few lines to install stack then. 

Thanks again

**Pull request merged**
