### PR TITLE
Fix detail.

### PR DESCRIPTION
**Pull request by MarcosPividori**

### CODE REVIEW

**Comment by AmeBel** [comment]
thanks

**Comment by AmeBel** [comment]
still failing 
```
[octool] Installing haskell dependencies in user space....
--2015-08-27 04:16:16--  https://raw.githubusercontent.com/opencog/atomspace/master/opencog/haskell/stack.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 103.245.222.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|103.245.222.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60 [text/plain]
Saving to: ‘stack.yaml’

     0K                                                       100% 19.8M=0s

2015-08-27 04:16:18 (19.8 MB/s) - ‘stack.yaml’ saved [60/60]

Downloading lts-2.18 build plan ...
Downloaded lts-2.18 build plan.
Caching build plan
Updating package index Hackage (mirrored at https://github.com/commercialhaskell/all-cabal-hashes.git) ...
Fetching package index ...
Fetched package index.
Populating index cache ...
Populated index cache.
stack will use the GHC on your PATH
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
No .cabal file found in directory /tmp/
The command '/bin/sh -c sudo chown -R opencog:opencog * .* ;     sudo chmod u+x configure-database.sh ;     /tmp/octool -s' returned a non-zero code: 1
---- Finished build of opencog/opencog-deps ----
```

https://hub.docker.com/r/opencog/opencog-deps/builds/btas4ghh79duyvrwgnjt7v/

**Comment by ngeiswei** [comment]
Oh, I see, if the docket fails then CI can't even run the compiling test, right?

**Comment by AmeBel** [comment]
not  sure how docker-hub deals with build failures. Let me check"

**Comment by AmeBel** [comment]
The image used for opencog repo is not affected, as its build depends on the succesful completion of the image used for atomspace and cogutils that is failing.

When a build fails there the previous build isn't touched ,  as is the case on pc usage. Thus circle-ci isn't affected.

**Comment by MarcosPividori** [comment]
Hi,
It should work fine now, after: https://github.com/opencog/ocpkg/pull/24
Sorry for those errors. It wasn't easy to predict them.
Thanks,
Marcos

**Pull request merged**
