### PR TITLE
Detail to improve Haddock documentation.

### PR DESCRIPTION
**Pull request by MarcosPividori**

### CODE REVIEW

**Comment by AmeBel** [comment]
after this merge docker builds are failing with
```
GHC version mismatched, found 7.8.4 (x86_64), but expected version 7.10.2 (x86_64) (based on resolver setting in /home/opencog/.stack/global/stack.yaml). Try running stack setup

```

refer to https://hub.docker.com/r/opencog/opencog-deps/builds/buqjggipgndgeavvgd7xmsg/  for details.

Need fix

**Comment by MarcosPividori** [comment]
Sorry,
Done! https://github.com/opencog/ocpkg/pull/23

**Comment by ngeiswei** [comment]
Sorry for merging too fast. Isn't CI supposed to test the branch (if that would have helped at all), BTW?

**Comment by AmeBel** [comment]
never thought of adding a test for the bash script, There are frameworks for testing bash scripts. Or do a docker image build instead. Sure

**Pull request merged**
